services:
  php:
    image: php:7.4-apache
    container_name: php
    ports:
      - "4500:80"
    volumes:
      - /home/arkantos/docker-apache-php7.2-mysql/www:/var/www/html
    links:
      - db

  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3333:3306"
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_DATABASE: eborges
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"   
  